<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class AdminSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create admin test list
        $admin = User::create([
            'name' => 'Romaric',
            'firstname' => 'G.',
            'slug' => Str::slug('Romaric G'),
            'email'=> 'admin@gmail.com',
            'password' => bcrypt('password'),
            'role' => 'admin', 
            'is_global_admin' => 1, // Is global admin
            'telephone' => '(+225) 01 0000 0000',
            'whatsapp' => '(+225) 01 0000 0000',
            'pays' => 'Côte d\'ivoire',
        ]);

        $admin->addMedia(public_path().'/admin/assets/img/avatar-user.png')
              ->preservingOriginal()
              ->toMediaCollection('avatar');

        User::create([
            'name' => 'Samuel',
            'firstname' => 'Romi',
            'slug' => Str::slug('Samuel Romi'),
            'email'=> 'sami@gmail.com',
            'password' => bcrypt('password'),
            'role' => 'admin',
            'telephone' => '(+225) 01 0000 0000',
            'pays' => 'Côte d\'ivoire',
        ]);

        // Creat other users
        $users = [
            // Manager list
            [
                'name' => 'Koné',
                'firstname' => 'Mohamed',
                'slug' => Str::slug('Mohamed Koné'),
                'email'=> 'manager-1@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'manager',
                'code' => 'CO-101',
                'manager_id' => 1,
                'activity_sector_id' => 1,
                'pays' => 'Côte d\'ivoire',
                'Ville' => 'Abidjan',
                'diplome' => 'BAC +4',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/manager-1.png',
            ],
            [
                'name' => 'Ouattara',
                'firstname' => 'Aboulay',
                'slug' => Str::slug('Ouattara Aboulay'),
                'email'=> 'manager-2@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'manager',
                'code' => 'CO-102',
                'manager_id' => 2,
                'activity_sector_id' => 1,
                'pays' => 'Togo',
                'Ville' => 'Cotonou',
                'diplome' => 'BAC +2',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/manager-2.png',
            ],
            [
                'name' => 'Dupont',
                'firstname' => 'Cédric',
                'slug' => Str::slug('cedric dupont'),
                'email'=> 'manager-3@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'manager',
                'code' => 'CO-103',
                'manager_id' => 3,
                'activity_sector_id' => 2,
                'pays' => 'Burkina Faso',
                'Ville' => 'Ouagadougou',
                'diplome' => 'BAC',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/manager-3.png',
            ],
            [
                'name' => 'Mazouli',
                'firstname' => 'Konaporé',
                'slug' => Str::slug('Mazouli Kanaporé'),
                'email'=> 'manager-4@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'manager',
                'code' => 'CO-104',
                'manager_id' => 4,
                'activity_sector_id' => 2,
                'pays' => 'Ghana',
                'Ville' => 'Accra',
                'diplome' => 'Licence',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/manager-1.png',
            ],
            [
                'name' => 'Tabouret',
                'firstname' => 'Mazeraty',
                'slug' => Str::slug('Tabouret Mazeraty'),
                'email'=> 'manager-5@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'manager',
                'code' => 'CO-105',
                'manager_id' => 5,
                'activity_sector_id' => 3,
                'pays' => 'Tunisie',
                'Ville' => 'Tunis',
                'diplome' => 'Master',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/manager-2.png',
            ],
            [
                'name' => 'Chapeauté',
                'firstname' => 'Olivier',
                'slug' => Str::slug('Chapeauté Olivier'),
                'email'=> 'manager-6@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'manager',
                'code' => 'CO-106',
                'manager_id' => 6,
                'activity_sector_id' => 3,
                'pays' => 'Côte d\'ivoire',
                'Ville' => 'Yammousoukro',
                'diplome' => 'BAC +4',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/manager-1.png',
            ],
            [
                'name' => 'Colisier',
                'firstname' => 'Marise',
                'slug' => Str::slug('Colisier Marise'),
                'email'=> 'manager-7@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'manager',
                'code' => 'CO-107',
                'manager_id' => 7,
                'activity_sector_id' => 3,
                'pays' => 'Togo',
                'Ville' => 'Lomé',
                'diplome' => 'BAC +4',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/manager-3.png',
            ],
            [
                'name' => 'Dogoté',
                'firstname' => 'Alain',
                'slug' => Str::slug('Dogoté Alain'),
                'email'=> 'manager-8@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'manager',
                'code' => 'CO-108',
                'manager_id' => 8,
                'activity_sector_id' => 2,
                'pays' => 'Côte d\'ivoire',
                'Ville' => 'Bouaké',
                'diplome' => 'BAC',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/manager-2.png',
            ],
            // Commercial list
            [
                'name' => 'Zadi',
                'firstname' => 'Normandine',
                'slug' => Str::slug('Zadi Normandine'),
                'email'=> 'commercial-1@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'commercial',
                'code' => 'CO-109',
                'commercial_id' => 1,
                'activity_sector_id' => 2,
                'pays' => 'Côte d\'ivoire',
                'Ville' => 'San-Pédro',
                'diplome' => 'Licence',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/commercial-1.png',
            ],
            [
                'name' => 'Francoise',
                'firstname' => 'Laboisroue',
                'slug' => Str::slug('Francoise Leboiroue'),
                'email'=> 'commercial-2@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'commercial',
                'code' => 'CO-110',
                'commercial_id' => 2,
                'activity_sector_id' => 2,
                'pays' => 'Mali',
                'Ville' => 'Bamako',
                'diplome' => 'BAC +2',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/commercial-2.png',
            ],
            [
                'name' => 'Dumatin',
                'firstname' => 'Monsucre',
                'slug' => Str::slug('Dogoté Alain'),
                'email'=> 'commercial-3@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'commercial',
                'code' => 'CO-111',
                'commercial_id' => 3,
                'activity_sector_id' => 1,
                'pays' => 'Afrique du sud',
                'Ville' => 'Prétoria',
                'diplome' => 'BECP',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/commercial-3.png',
            ],
            [
                'name' => 'Serise',
                'firstname' => 'André',
                'slug' => Str::slug('Serise André'),
                'email'=> 'commercial-4@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'commercial',
                'code' => 'CO-112',
                'commercial_id' => 4,
                'activity_sector_id' => 3,
                'pays' => 'Côte d\'ivoire',
                'Ville' => 'Sassandra',
                'diplome' => 'BAC +4',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/commercial-1.png',
            ],
            // Entreprise list
            [
                'name' => 'Kambiré',
                'firstname' => 'Machoiron',
                'slug' => Str::slug('Kambiré Machoiron'),
                'email'=> 'entreprise-1@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'business',
                'code' => 'CO-113',
                'business_id' => 1,
                'activity_sector_id' => 1,
                'pays' => 'Togo',
                'Ville' => 'Lomé',
                'diplome' => 'BAC +4',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/avatar.png',
            ],
            [
                'name' => 'Niamkey',
                'firstname' => 'Moise',
                'slug' => Str::slug('Niamkey Moise'),
                'email'=> 'entrepise-2@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'business',
                'code' => 'CO-114',
                'business_id' => 2,
                'activity_sector_id' => 2,
                'pays' => 'Côte d\'ivoire',
                'Ville' => 'Séguéla',
                'diplome' => 'BAC +2',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/avatar.png',
            ],
            [
                'name' => 'Latriche',
                'firstname' => 'Bomayé',
                'slug' => Str::slug('Latriche Bomayé'),
                'email'=> 'entrepise-3@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'business',
                'code' => 'CO-115',
                'business_id' => 3,
                'activity_sector_id' => 3,
                'pays' => 'Benin',
                'Ville' => 'Cotonou',
                'diplome' => 'BAC +4',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/avatar.png',
            ],
            [
                'name' => 'Karlyto',
                'firstname' => 'Sarkozy',
                'slug' => Str::slug('Karlyto Sarkozy'),
                'email'=> 'entrepise-4@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'business',
                'code' => 'CO-116',
                'business_id' => 4,
                'activity_sector_id' => 2,
                'pays' => 'Côte d\'ivoire',
                'Ville' => 'Korhogo',
                'diplome' => 'Licence',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/avatar.png',
            ],
            [
                'name' => 'Oulia',
                'firstname' => 'Martin',
                'slug' => Str::slug('Oulia Martin'),
                'email'=> 'entrepise-5@gmail.com',
                'password' => bcrypt('password'),
                'role' => 'business',
                'code' => 'CO-117',
                'business_id' => 5,
                'activity_sector_id' => 2,
                'pays' => 'Côte d\'ivoire',
                'Ville' => 'San-Pédro',
                'diplome' => 'Licence',
                'telephone' => '(+225) 01 0000 0000',
                'whatsapp' => '(+225) 01 0000 0000',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
                'avatar' => public_path() . '/admin/assets/img/avatar.png',
            ],
        ];

        foreach ($users as $key => $item) {
            $data = collect($item)->except('avatar');
            $user = User::create($data->toArray());
            
            $user->addMedia($item['avatar'])
                ->preservingOriginal()
                ->toMediaCollection('avatar');
        }
    }
}
